import { createFacebookPhaseHelpers } from "./facebook-phase.mjs";
import { createJobOrchestrator } from "./orchestrator.mjs";
import { createPackageGenerator } from "./package-generator.mjs";
import { createPostingMachine } from "./posting-machine.mjs";
import { createWordPressJobClient } from "./wordpress-jobs.mjs";

export function createJobsHelpers(deps) {
  const {
    WORKER_VERSION,
    config,
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    formatError,
    log,
    resolveCanonicalContentPackage,
    resolveFacebookDefaultCtas,
    resolveFacebookChannelAdapter,
    toInt,
    wpRequest,
    buildChannelProfile,
    buildFacebookGroupsDraft,
    buildPinterestDraft,
    CHANNEL_ADAPTER_CONTRACT_VERSION,
    CONTENT_PACKAGE_CONTRACT_VERSION,
    PROMPT_VERSION,
    cleanText,
    ensureSocialPackCoverage,
    generateCoreArticlePackage,
    generateSocialCandidatePool,
    isPlainObject,
    normalizeFacebookDistribution,
    normalizeGeneratedPayload,
    resolvePreferredAngle,
    resolvePublicationProfile,
    resolveSelectedFacebookPages,
    resolveTypedGuidance,
    summarizeSelectedSocialPack,
    syncGeneratedContractContainers,
    assertFacebookConfigured,
    assertQualityGate,
    assertRecipeDistributionTargets,
    buildFallbackFacebookCaption,
    buildQualitySummary,
    ensureJobImages,
    ensureOpenAiConfigured,
    firstAttachment,
    firstSuccessfulDistributionResult,
    hydrateStoredGeneratedPayload,
    isFutureUtcTimestamp,
    mergeSettings,
    mergeValidatorSummary,
    publishFacebookDistribution,
    seedLegacyFacebookDistribution,
    summarizeFacebookFailures,
  } = deps;

  const facebookPhaseHelpers = createFacebookPhaseHelpers({
    assertRecipeDistributionTargets,
    buildFallbackFacebookCaption,
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    firstSuccessfulDistributionResult,
    resolveFacebookChannelAdapter,
    resolvePreferredAngle,
    resolveSelectedFacebookPages,
    seedLegacyFacebookDistribution,
    syncGeneratedContractContainers,
  });

  const wordPressJobClient = createWordPressJobClient({
    WORKER_VERSION,
    config,
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    formatError,
    log,
    resolveCanonicalContentPackage,
    resolveFacebookDefaultCtas,
    resolveFacebookChannelAdapter,
    toInt,
    wpRequest,
  });

  const packageGenerator = createPackageGenerator({
    buildChannelProfile,
    buildFacebookGroupsDraft,
    buildPinterestDraft,
    CHANNEL_ADAPTER_CONTRACT_VERSION,
    CONTENT_PACKAGE_CONTRACT_VERSION,
    PROMPT_VERSION,
    cleanText,
    ensureSocialPackCoverage,
    formatError,
    generateCoreArticlePackage,
    generateSocialCandidatePool,
    isPlainObject,
    log,
    normalizeFacebookDistribution,
    normalizeGeneratedPayload,
    resolveCanonicalContentPackage,
    resolvePreferredAngle,
    resolvePublicationProfile,
    resolveSelectedFacebookPages,
    resolveTypedGuidance,
    summarizeSelectedSocialPack,
    syncGeneratedContractContainers,
  });

  const postingMachine = createPostingMachine({
    assertFacebookConfigured,
    completeJob: (...args) => wordPressJobClient.completeJob(...args),
    finalizeFacebookPhaseState: (...args) => facebookPhaseHelpers.finalizeFacebookPhaseState(...args),
    formatError,
    log,
    publishBlogPost: (...args) => wordPressJobClient.publishBlogPost(...args),
    publishFacebookDistribution,
    resolveSelectedFacebookPages,
    safeFailJob: (...args) => wordPressJobClient.safeFailJob(...args),
    seedLegacyFacebookDistribution,
    summarizeFacebookFailures,
    toInt,
    updateJobProgress: (...args) => wordPressJobClient.updateJobProgress(...args),
  });

  const jobOrchestrator = createJobOrchestrator({
    assertQualityGate,
    assertRecipeDistributionTargets,
    buildQualitySummary,
    claimNextJob: (...args) => wordPressJobClient.claimNextJob(...args),
    ensureJobImages,
    ensureOpenAiConfigured,
    ensureSocialPackCoverage,
    firstAttachment,
    formatError,
    generatePackage: (...args) => packageGenerator.generatePackage(...args),
    hydrateStoredGeneratedPayload,
    idleHeartbeatState: (...args) => wordPressJobClient.idleHeartbeatState(...args),
    isFutureUtcTimestamp,
    log,
    mergeSettings,
    mergeValidatorSummary,
    normalizeGeneratedPayload,
    postingMachine,
    refreshFacebookPhaseState: (...args) => facebookPhaseHelpers.refreshFacebookPhaseState(...args),
    resolveCanonicalContentPackage,
    safeFailJob: (...args) => wordPressJobClient.safeFailJob(...args),
    toInt,
    updateJobProgress: (...args) => wordPressJobClient.updateJobProgress(...args),
  });

  return {
    jobOrchestrator,
    packageGenerator,
    postingMachine,
    wordPressJobClient,
  };
}
