import { createJobOrchestrator } from "./orchestrator.mjs";
import { createPackageGenerator } from "./package-generator.mjs";
import { createWordPressJobClient } from "./wordpress-jobs.mjs";

export function createJobsHelpers(deps) {
  const {
    WORKER_VERSION,
    config,
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    formatError,
    log,
    resolveCanonicalContentPackage,
    resolveFacebookChannelAdapter,
    toInt,
    wpRequest,
    buildChannelProfile,
    buildFacebookGroupsDraft,
    buildPinterestDraft,
    CHANNEL_ADAPTER_CONTRACT_VERSION,
    CONTENT_PACKAGE_CONTRACT_VERSION,
    PROMPT_VERSION,
    cleanText,
    ensureSocialPackCoverage,
    generateCoreArticlePackage,
    generateSocialCandidatePool,
    isPlainObject,
    normalizeFacebookDistribution,
    normalizeGeneratedPayload,
    resolvePreferredAngle,
    resolvePublicationProfile,
    resolveSelectedFacebookPages,
    resolveTypedGuidance,
    summarizeSelectedSocialPack,
    syncGeneratedContractContainers,
    assertFacebookConfigured,
    assertQualityGate,
    assertRecipeDistributionTargets,
    buildFallbackFacebookCaption,
    buildQualitySummary,
    ensureJobImages,
    ensureOpenAiConfigured,
    firstAttachment,
    firstSuccessfulDistributionResult,
    hydrateStoredGeneratedPayload,
    isFutureUtcTimestamp,
    mergeSettings,
    mergeValidatorSummary,
    publishBlogPost,
    publishFacebookDistribution,
    safeFailJob,
    seedLegacyFacebookDistribution,
    summarizeFacebookFailures,
    updateJobProgress,
  } = deps;

  const wordPressJobClient = createWordPressJobClient({
    WORKER_VERSION,
    config,
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    formatError,
    log,
    resolveCanonicalContentPackage,
    resolveFacebookChannelAdapter,
    toInt,
    wpRequest,
  });

  const packageGenerator = createPackageGenerator({
    buildChannelProfile,
    buildFacebookGroupsDraft,
    buildPinterestDraft,
    CHANNEL_ADAPTER_CONTRACT_VERSION,
    CONTENT_PACKAGE_CONTRACT_VERSION,
    PROMPT_VERSION,
    cleanText,
    ensureSocialPackCoverage,
    formatError,
    generateCoreArticlePackage,
    generateSocialCandidatePool,
    isPlainObject,
    log,
    normalizeFacebookDistribution,
    normalizeGeneratedPayload,
    resolveCanonicalContentPackage,
    resolvePreferredAngle,
    resolvePublicationProfile,
    resolveSelectedFacebookPages,
    resolveTypedGuidance,
    summarizeSelectedSocialPack,
    syncGeneratedContractContainers,
  });

  const jobOrchestrator = createJobOrchestrator({
    assertFacebookConfigured,
    assertQualityGate,
    assertRecipeDistributionTargets,
    buildFallbackFacebookCaption,
    buildQualitySummary,
    claimNextJob: (...args) => wordPressJobClient.claimNextJob(...args),
    completeJob: (...args) => wordPressJobClient.completeJob(...args),
    deriveLegacyFacebookCaptionMirror,
    deriveLegacyGroupShareKitMirror,
    ensureJobImages,
    ensureOpenAiConfigured,
    ensureSocialPackCoverage,
    firstAttachment,
    firstSuccessfulDistributionResult,
    formatError,
    generatePackage: (...args) => packageGenerator.generatePackage(...args),
    hydrateStoredGeneratedPayload,
    idleHeartbeatState: (...args) => wordPressJobClient.idleHeartbeatState(...args),
    isFutureUtcTimestamp,
    log,
    mergeSettings,
    mergeValidatorSummary,
    normalizeGeneratedPayload,
    publishBlogPost: (...args) => wordPressJobClient.publishBlogPost(...args),
    publishFacebookDistribution,
    resolveCanonicalContentPackage,
    resolveFacebookChannelAdapter,
    resolvePreferredAngle,
    resolveSelectedFacebookPages,
    safeFailJob: (...args) => wordPressJobClient.safeFailJob(...args),
    seedLegacyFacebookDistribution,
    summarizeFacebookFailures,
    syncGeneratedContractContainers,
    toInt,
    updateJobProgress: (...args) => wordPressJobClient.updateJobProgress(...args),
  });

  return {
    jobOrchestrator,
    packageGenerator,
    wordPressJobClient,
  };
}
