import { createContentQualityUtils } from "./quality-utils.mjs";
import { createGenerationRunner } from "./generation-runner.mjs";
import { createImageAssetHelpers } from "./image-assets.mjs";
import { createImagePromptHelpers } from "./image-prompts.mjs";
import { createPageFlowHelpers } from "./page-flow.mjs";
import { createPageSplittingHelpers } from "./page-splitting.mjs";
import { createPageContentHelpers } from "./pages.mjs";
import { createPromptBuilders } from "./prompts.mjs";
import { createSocialSignalHelpers } from "./social-signals.mjs";
import { createArticleValidationHelpers } from "../quality/article-validator.mjs";
import { createQualityEntryPoints } from "../quality/entrypoints.mjs";
import { createValidatorSummaryHelpers } from "../quality/validator-summary.mjs";

export function createContentHelpers(deps) {
  const {
    angleDefinition,
    angleDefinitionsForType,
    buildAngleSequence,
    buildFallbackCaption,
    buildContentTypeProfile,
    buildFacebookPostMessage,
    buildInternalLinkMarkup,
    buildPageAnglePlan,
    cleanMultilineText,
    cleanText,
    config,
    countInternalLinks,
    countWords,
    desiredSocialSignalTargets,
    ensureOpenAiConfigured,
    ensureStringArray,
    escapeHtml,
    extractOpeningParagraphText,
    firstSentence,
    formatError,
    generateImageBase64,
    internalLinkTargetsForJob,
    isPlainObject,
    joinNaturalList,
    log,
    normalizeAngleKey,
    normalizeHtml,
    normalizeSlug,
    normalizeSocialFingerprint,
    normalizeSocialLineFingerprint,
    normalizeSocialPack,
    parseJsonObject,
    readGeneratedArray,
    readGeneratedString,
    requestOpenAiChat,
    resolveCanonicalContentPackage,
    resolveContentSitePolicy,
    resolveFacebookChannelAdapter,
    resolveFacebookTargets,
    resolveTypedGuidance,
    runBuildContentPackageQualitySummary,
    runBuildDormantChannelQualitySummary,
    runBuildEditorialReadinessSummary,
    runBuildFacebookChannelQualitySummary,
    runBuildFallbackSocialPack,
    runBuildQualitySummary,
    runCollectCanonicalContractChecks,
    runDesiredSocialSignalTargets,
    runEnsureSocialPackCoverage,
    runExtractGeneratedContractVersions,
    runExtractValidatorSummary,
    runFilterChannelWarningChecks,
    runFindBestSocialCandidateIndex,
    runGenerateCoreArticlePackage,
    runGenerateSocialCandidatePool,
    runIsCanonicalContractVersion,
    runQualityCheckReasonMessage,
    runSummarizeArticleStage,
    runSummarizeSelectedSocialPack,
    runSummarizeSocialCandidatePool,
    scoreSocialVariant,
    sentenceCase,
    sharedWordsRatio,
    socialVariantActionabilitySignal,
    socialVariantAnchorSignal,
    socialVariantConsequenceSignal,
    socialVariantContrastSignal,
    socialVariantConversationSignal,
    socialVariantCuriositySignal,
    socialVariantHabitShiftSignal,
    socialVariantIdentityShiftSignal,
    socialVariantImmediacySignal,
    socialVariantLooksWeak,
    socialVariantNoveltyScore,
    socialVariantPainPointSignal,
    socialVariantPayoffSignal,
    socialVariantPromiseFocusSignal,
    socialVariantPromiseSyncSignal,
    socialVariantProofSignal,
    socialVariantRelatabilitySignal,
    socialVariantResolvesEarly,
    socialVariantSavvySignal,
    socialVariantScannabilitySignal,
    socialVariantSelfRecognitionSignal,
    socialVariantSpecificityScore,
    socialVariantTwoStepSignal,
    stripHookEchoFromCaption,
    summarizeSelectedSocialPack,
    toInt,
    trimText,
    trimWords,
    wpRequest,
    normalizeGeneratedPayload,
    syncGeneratedContractContainers,
  } = deps;

  const contentQualityUtils = createContentQualityUtils({
    cleanText,
    cleanMultilineText,
    trimWords,
    countWords,
    normalizeSlug,
    sharedWordsRatio,
  });

  const pageFlowHelpers = createPageFlowHelpers({
    cleanText,
    cleanMultilineText,
    trimText,
    trimWords,
    firstSentence,
    isPlainObject,
    normalizePageFlowLabelFingerprint: contentQualityUtils.normalizePageFlowLabelFingerprint,
    pageFlowLabelLooksStrong: contentQualityUtils.pageFlowLabelLooksStrong,
    pageFlowSummaryLooksStrong: contentQualityUtils.pageFlowSummaryLooksStrong,
  });

  const pageContentHelpers = createPageContentHelpers({
    buildInternalLinkMarkup,
    countInternalLinks,
    internalLinkTargetsForJob,
    normalizeHtml,
    resolveContentSitePolicy,
  });

  const pageSplittingHelpers = createPageSplittingHelpers({
    cleanText,
    cleanMultilineText,
    countWords,
    escapeHtml,
    extractFirstHeading: pageFlowHelpers.extractFirstHeading,
    isPlainObject,
    mergeContentPagesIntoHtml: pageContentHelpers.mergeContentPagesIntoHtml,
    normalizeContentPageItem: pageContentHelpers.normalizeContentPageItem,
    normalizeHtml,
    pageStartsWithExpectedLead: contentQualityUtils.pageStartsWithExpectedLead,
    readGeneratedArray,
    readGeneratedString,
  });

  const socialSignalHelpers = createSocialSignalHelpers({
    cleanText,
    trimText,
    trimWords,
    ensureStringArray,
    joinNaturalList,
    sharedWordsRatio,
    sentenceCase,
    firstSentence,
    normalizeGeneratedPageFlow: pageFlowHelpers.normalizeGeneratedPageFlow,
    splitHtmlIntoPages: pageSplittingHelpers.splitHtmlIntoPages,
    isPlainObject,
  });

  const imagePromptHelpers = createImagePromptHelpers({
    cleanText,
    cleanMultilineText,
    resolveCanonicalContentPackage,
    trimText,
  });

  const imageAssetHelpers = createImageAssetHelpers({
    buildImagePrompt: imagePromptHelpers.buildImagePrompt,
    ensureOpenAiConfigured,
    generateImageBase64,
    log,
    normalizeSlug,
    resolveCanonicalContentPackage,
    wpRequest,
  });

  const validatorSummaryHelpers = createValidatorSummaryHelpers({
    cleanText,
    isPlainObject,
    syncGeneratedContractContainers,
  });

  const articleValidationHelpers = createArticleValidationHelpers({
    cleanText,
    resolveCanonicalContentPackage,
  });

  const promptBuilders = createPromptBuilders({
    buildInternalLinkMarkup,
    resolveTypedGuidance,
    internalLinkTargetsForJob,
    resolveContentSitePolicy,
    buildArticleSocialSignals: socialSignalHelpers.buildArticleSocialSignals,
    cleanText,
    cleanMultilineText,
    trimText,
    normalizeSocialLineFingerprint,
    buildPageAnglePlan,
    angleDefinitionsForType,
    config,
  });

  const qualityEntryPoints = createQualityEntryPoints({
    runBuildContentPackageQualitySummary,
    runBuildDormantChannelQualitySummary,
    runBuildEditorialReadinessSummary,
    runBuildFacebookChannelQualitySummary,
    runBuildQualitySummary,
    runBuildFallbackSocialPack,
    runCollectCanonicalContractChecks,
    runDesiredSocialSignalTargets,
    runEnsureSocialPackCoverage,
    runExtractGeneratedContractVersions,
    runExtractValidatorSummary,
    runFilterChannelWarningChecks,
    runFindBestSocialCandidateIndex,
    runIsCanonicalContractVersion,
    runQualityCheckReasonMessage,
    runSummarizeArticleStage,
    runSummarizeSelectedSocialPack,
    runSummarizeSocialCandidatePool,
    buildQualityModuleDeps: () => ({
      angleDefinitionsForType,
      buildArticleSocialSignals: socialSignalHelpers.buildArticleSocialSignals,
      buildContentTypeProfile,
      cleanText,
      classifySocialHookForm: deps.classifySocialHookForm,
      countInternalLinks,
      desiredSocialSignalTargets,
      ensureStringArray,
      excerptAddsNewValue: contentQualityUtils.excerptAddsNewValue,
      excerptClickSignalScore: contentQualityUtils.excerptClickSignalScore,
      extractOpeningParagraphText,
      frontLoadedClickSignalScore: contentQualityUtils.frontLoadedClickSignalScore,
      headlineSpecificityScore: contentQualityUtils.headlineSpecificityScore,
      isPlainObject,
      normalizeCaptionOpeningFingerprint: deps.normalizeCaptionOpeningFingerprint,
      normalizeGeneratedPageFlow: pageFlowHelpers.normalizeGeneratedPageFlow,
      normalizeHookFingerprint: deps.normalizeHookFingerprint,
      normalizePageFlowLabelFingerprint: contentQualityUtils.normalizePageFlowLabelFingerprint,
      normalizeSocialFingerprint: deps.normalizeSocialFingerprint,
      normalizeAngleKey,
      openingParagraphAddsNewValue: contentQualityUtils.openingParagraphAddsNewValue,
      openingPromiseAlignmentScore: contentQualityUtils.openingPromiseAlignmentScore,
      pageFlowLabelLooksStrong: contentQualityUtils.pageFlowLabelLooksStrong,
      pageFlowSummaryLooksStrong: contentQualityUtils.pageFlowSummaryLooksStrong,
      pageStartsWithExpectedLead: contentQualityUtils.pageStartsWithExpectedLead,
      resolveCanonicalContentPackage,
      resolveContentSitePolicy,
      resolveFacebookChannelAdapter,
      resolveFacebookTargets,
      seoDescriptionSignalScore: contentQualityUtils.seoDescriptionSignalScore,
      socialVariantLooksWeak,
      splitHtmlIntoPages: pageSplittingHelpers.splitHtmlIntoPages,
      summarizeSelectedSocialPack,
      titleLooksStrong: contentQualityUtils.titleLooksStrong,
      toInt,
    }),
    buildFacebookQualityModuleDeps: () => ({
      angleDefinitionsForType,
      buildArticleSocialSignals: socialSignalHelpers.buildArticleSocialSignals,
      buildFallbackCaption,
      buildAngleSequence,
      angleDefinition,
      buildFacebookPostMessage,
      classifySocialHookForm: deps.classifySocialHookForm,
      cleanMultilineText,
      cleanText,
      frontLoadedClickSignalScore: contentQualityUtils.frontLoadedClickSignalScore,
      normalizeAngleKey,
      normalizeCaptionOpeningFingerprint: deps.normalizeCaptionOpeningFingerprint,
      normalizeHookFingerprint: deps.normalizeHookFingerprint,
      normalizeSocialFingerprint: deps.normalizeSocialFingerprint,
      normalizeSocialPack,
      scoreSocialVariant,
      sharedWordsRatio,
      socialVariantActionabilitySignal,
      socialVariantAnchorSignal,
      socialVariantConsequenceSignal,
      socialVariantContrastSignal,
      socialVariantConversationSignal,
      socialVariantCuriositySignal,
      socialVariantHabitShiftSignal,
      socialVariantIdentityShiftSignal,
      socialVariantImmediacySignal,
      socialVariantLooksWeak,
      socialVariantNoveltyScore,
      socialVariantPainPointSignal,
      socialVariantPayoffSignal,
      socialVariantPromiseFocusSignal,
      socialVariantPromiseSyncSignal,
      socialVariantProofSignal,
      socialVariantRelatabilitySignal,
      socialVariantResolvesEarly,
      socialVariantSavvySignal,
      socialVariantScannabilitySignal,
      socialVariantSelfRecognitionSignal,
      socialVariantSpecificityScore,
      socialVariantTwoStepSignal,
      stripHookEchoFromCaption,
    }),
    buildArticleQualityModuleDeps: () => ({
      cleanText,
      countInternalLinks,
      countWords,
      ensureStringArray,
      excerptAddsNewValue: contentQualityUtils.excerptAddsNewValue,
      excerptClickSignalScore: contentQualityUtils.excerptClickSignalScore,
      extractOpeningParagraphText,
      frontLoadedClickSignalScore: contentQualityUtils.frontLoadedClickSignalScore,
      headlineSpecificityScore: contentQualityUtils.headlineSpecificityScore,
      isPlainObject,
      normalizeGeneratedPageFlow: pageFlowHelpers.normalizeGeneratedPageFlow,
      normalizePageFlowLabelFingerprint: contentQualityUtils.normalizePageFlowLabelFingerprint,
      openingParagraphAddsNewValue: contentQualityUtils.openingParagraphAddsNewValue,
      openingPromiseAlignmentScore: contentQualityUtils.openingPromiseAlignmentScore,
      pageFlowLabelLooksStrong: contentQualityUtils.pageFlowLabelLooksStrong,
      pageFlowSummaryLooksStrong: contentQualityUtils.pageFlowSummaryLooksStrong,
      pageStartsWithExpectedLead: contentQualityUtils.pageStartsWithExpectedLead,
      resolveCanonicalContentPackage,
      resolveContentSitePolicy,
      seoDescriptionSignalScore: contentQualityUtils.seoDescriptionSignalScore,
      splitHtmlIntoPages: pageSplittingHelpers.splitHtmlIntoPages,
      titleLooksStrong: contentQualityUtils.titleLooksStrong,
    }),
  });

  const generationRunner = createGenerationRunner({
    angleDefinitionsForType,
    buildCoreArticlePrompt: promptBuilders.buildCoreArticlePrompt,
    buildSocialCandidatePrompt: promptBuilders.buildSocialCandidatePrompt,
    formatError,
    normalizeGeneratedPayload,
    normalizeSocialPack,
    parseJsonObject,
    requestOpenAiChat,
    runGenerateCoreArticlePackage,
    runGenerateSocialCandidatePool,
    summarizeArticleStage: qualityEntryPoints.summarizeArticleStage,
    summarizeSocialCandidatePool: qualityEntryPoints.summarizeSocialCandidatePool,
    validateGeneratedPayload: articleValidationHelpers.validateGeneratedPayload,
  });

  return {
    buildImagePrompt: imagePromptHelpers.buildImagePrompt,
    ensureJobImages: imageAssetHelpers.ensureJobImages,
    contentQualityUtils,
    pageFlowHelpers,
    pageContentHelpers,
    pageSplittingHelpers,
    socialSignalHelpers,
    validatorSummaryHelpers,
    articleValidationHelpers,
    promptBuilders,
    qualityEntryPoints,
    generationRunner,
  };
}
